"""widen survey gender

Revision ID: 0002
Revises: 0001
"""

import sqlalchemy as sa

from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("survey_responses", "gender", existing_type=sa.VARCHAR(length=15), type_=sa.String(length=20), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("survey_responses", "gender", existing_type=sa.String(length=20), type_=sa.VARCHAR(length=15), existing_nullable=True)
    # ### end Alembic commands ###
