"""Static content for the seed: Kabul-flavoured businesses, products and the TAM/UTAUT questionnaire."""

CATEGORIES = [
    "Food & Bakery",
    "Fresh Produce",
    "Dry Fruits & Nuts",
    "Textiles & Clothing",
    "Electronics & Phones",
    "Home & Kitchen",
    "Construction Supplies",
    "Handicrafts & Carpets",
]

# category -> [(product name, unit, low price AFN, high price AFN)]
PRODUCTS = {
    "Food & Bakery": [
        ("Afghan naan", "piece", 10, 20),
        ("Bolani (potato)", "piece", 30, 50),
        ("Mantu tray", "tray", 250, 400),
        ("Kulcha cookies", "box", 120, 220),
        ("Sheer khurma", "kg", 300, 450),
        ("Bulani gandana", "piece", 25, 45),
        ("Jalebi", "kg", 180, 260),
    ],
    "Fresh Produce": [
        ("Tomatoes", "kg", 40, 80),
        ("Potatoes", "kg", 25, 45),
        ("Onions", "kg", 20, 40),
        ("Pomegranates (Kandahari)", "kg", 120, 200),
        ("Grapes (Kabuli)", "kg", 90, 160),
        ("Spinach", "bunch", 10, 20),
        ("Carrots", "kg", 25, 45),
    ],
    "Dry Fruits & Nuts": [
        ("Raisins (green)", "kg", 400, 650),
        ("Almonds", "kg", 900, 1300),
        ("Pistachios", "kg", 1400, 2000),
        ("Walnuts", "kg", 600, 900),
        ("Dried mulberries", "kg", 350, 550),
        ("Chickpea mix (nakhod)", "kg", 120, 200),
    ],
    "Textiles & Clothing": [
        ("Men's perahan tunban", "set", 1200, 2600),
        ("Women's dress (Kuchi)", "piece", 1800, 4500),
        ("Pakol hat", "piece", 350, 700),
        ("Wool shawl (patu)", "piece", 900, 2200),
        ("Children's school uniform", "set", 600, 1100),
        ("Fabric (per metre)", "metre", 150, 450),
    ],
    "Electronics & Phones": [
        ("Phone charger (fast)", "piece", 250, 500),
        ("Earphones", "piece", 150, 600),
        ("Power bank 10000mAh", "piece", 900, 1600),
        ("Phone case", "piece", 100, 300),
        ("LED bulb 12W", "piece", 80, 140),
        ("Solar lamp", "piece", 700, 1400),
    ],
    "Home & Kitchen": [
        ("Steel pot set", "set", 1500, 3200),
        ("Tea glasses (6)", "box", 180, 350),
        ("Plastic chairs", "piece", 350, 600),
        ("Floor cushion (toshak)", "piece", 800, 1500),
        ("Thermos flask", "piece", 450, 900),
        ("Gas burner", "piece", 600, 1300),
    ],
    "Construction Supplies": [
        ("Cement bag 50kg", "bag", 550, 700),
        ("Steel rebar 12mm", "piece", 420, 600),
        ("Paint 4L", "can", 900, 1800),
        ("Bricks (per 100)", "lot", 700, 1000),
        ("PVC pipe 2in", "piece", 250, 450),
        ("Door lock", "piece", 200, 600),
    ],
    "Handicrafts & Carpets": [
        ("Hand-knotted rug 2x3m", "piece", 12000, 38000),
        ("Embroidered cushion cover", "piece", 350, 800),
        ("Lapis lazuli ring", "piece", 1500, 4500),
        ("Turkmen-style bag", "piece", 900, 2500),
        ("Wood-carved box", "piece", 600, 1800),
        ("Turquoise necklace", "piece", 1200, 3600),
    ],
}

SHOPS = [  # (business name, primary category)
    ("Noor Bakery", "Food & Bakery"),
    ("Shahr-e-Naw Fresh Market", "Fresh Produce"),
    ("Mandawi Dry Fruits", "Dry Fruits & Nuts"),
    ("Chicken Street Textiles", "Textiles & Clothing"),
    ("Kabul Phone Corner", "Electronics & Phones"),
    ("Khair Khana Home Goods", "Home & Kitchen"),
    ("Darulaman Building Supply", "Construction Supplies"),
    ("Turquoise Mountain Crafts", "Handicrafts & Carpets"),
    ("Wazir Akbar Khan Sweets", "Food & Bakery"),
    ("Qala-e-Fatullah Produce", "Fresh Produce"),
    ("Bagh-e-Bala Nuts", "Dry Fruits & Nuts"),
    ("Mirwais Maidan Fabrics", "Textiles & Clothing"),
    ("Hamid Electronics", "Electronics & Phones"),
    ("Karte Se Kitchenware", "Home & Kitchen"),
    ("Pul-e-Sukhta Hardware", "Construction Supplies"),
    ("Rabia Balkhi Carpets", "Handicrafts & Carpets"),
    ("Taimani Tandoor", "Food & Bakery"),
    ("Kart-e-Char Greengrocer", "Fresh Produce"),
    ("Pamir Raisin House", "Dry Fruits & Nuts"),
    ("Sadaf Tailoring", "Textiles & Clothing"),
    ("Afghan Mobile Hub", "Electronics & Phones"),
    ("Shirpur Household", "Home & Kitchen"),
    ("Jada-e-Maiwand Cement", "Construction Supplies"),
    ("Kuchi Craft Collective", "Handicrafts & Carpets"),
    ("Dasht-e-Barchi Bakery", "Food & Bakery"),
    ("Microrayan Market Garden", "Fresh Produce"),
    ("Paghman Orchard Direct", "Dry Fruits & Nuts"),
    ("Zarnegar Dress Shop", "Textiles & Clothing"),
    ("Solar Kabul", "Electronics & Phones"),
    ("Bibi Mahro Kitchen Store", "Home & Kitchen"),
    ("Qargha Paint & Tools", "Construction Supplies"),
    ("Lapis Lazuli Gallery", "Handicrafts & Carpets"),
    ("Sarai Shahzada Spices Bakery", "Food & Bakery"),
    ("Company Fresh Fruits", "Fresh Produce"),
    ("Nangarhar Nuts Depot", "Dry Fruits & Nuts"),
    ("Ansari Wool Traders", "Textiles & Clothing"),
    ("Chaman-e-Hozori Electronics", "Electronics & Phones"),
    ("Khushal Khan Homeware", "Home & Kitchen"),
    ("Shar-e-Naw Lumber", "Construction Supplies"),
    ("Herat Silk Road Crafts", "Handicrafts & Carpets"),
]

FIRST = [
    "Ahmad",
    "Mohammad",
    "Hamid",
    "Nasrin",
    "Zahra",
    "Farid",
    "Sohaila",
    "Jawid",
    "Mariam",
    "Bashir",
    "Laila",
    "Rahim",
    "Shabnam",
    "Qais",
    "Fatima",
    "Nazir",
    "Parwin",
    "Sayed",
    "Hila",
    "Omid",
]
LAST = [
    "Ahmadi",
    "Noori",
    "Rahimi",
    "Karimi",
    "Safi",
    "Sadat",
    "Popal",
    "Barakzai",
    "Wardak",
    "Amiri",
    "Yousufi",
    "Stanikzai",
    "Hashimi",
    "Faizi",
    "Azizi",
]
DISTRICT_WEIGHTS = {
    "PD1": 3,
    "PD2": 4,
    "PD3": 3,
    "PD4": 6,
    "PD5": 4,
    "PD6": 3,
    "PD7": 3,
    "PD8": 4,
    "PD10": 4,
    "PD11": 2,
    "PD12": 2,
    "PD13": 2,
    "PD15": 2,
    "PD16": 1,
    "PD17": 1,
    "PD22": 1,
}
