"""Static content for the seed: Kabul-flavoured businesses, products and the TAM/UTAUT questionnaire."""

CATEGORIES = [
    "Food & Bakery",
    "Fresh Produce",
    "Dry Fruits & Nuts",
    "Textiles & Clothing",
    "Electronics & Phones",
    "Home & Kitchen",
    "Construction Supplies",
    "Handicrafts & Carpets",
]

# category -> [(product name, unit, low price AFN, high price AFN)]
PRODUCTS = {
    "Food & Bakery": [
        ("Afghan naan", "piece", 10, 20),
        ("Bolani (potato)", "piece", 30, 50),
        ("Mantu tray", "tray", 250, 400),
        ("Kulcha cookies", "box", 120, 220),
        ("Sheer khurma", "kg", 300, 450),
        ("Bulani gandana", "piece", 25, 45),
        ("Jalebi", "kg", 180, 260),
    ],
    "Fresh Produce": [
        ("Tomatoes", "kg", 40, 80),
        ("Potatoes", "kg", 25, 45),
        ("Onions", "kg", 20, 40),
        ("Pomegranates (Kandahari)", "kg", 120, 200),
        ("Grapes (Kabuli)", "kg", 90, 160),
        ("Spinach", "bunch", 10, 20),
        ("Carrots", "kg", 25, 45),
    ],
    "Dry Fruits & Nuts": [
        ("Raisins (green)", "kg", 400, 650),
        ("Almonds", "kg", 900, 1300),
        ("Pistachios", "kg", 1400, 2000),
        ("Walnuts", "kg", 600, 900),
        ("Dried mulberries", "kg", 350, 550),
        ("Chickpea mix (nakhod)", "kg", 120, 200),
    ],
    "Textiles & Clothing": [
        ("Men's perahan tunban", "set", 1200, 2600),
        ("Women's dress (Kuchi)", "piece", 1800, 4500),
        ("Pakol hat", "piece", 350, 700),
        ("Wool shawl (patu)", "piece", 900, 2200),
        ("Children's school uniform", "set", 600, 1100),
        ("Fabric (per metre)", "metre", 150, 450),
    ],
    "Electronics & Phones": [
        ("Phone charger (fast)", "piece", 250, 500),
        ("Earphones", "piece", 150, 600),
        ("Power bank 10000mAh", "piece", 900, 1600),
        ("Phone case", "piece", 100, 300),
        ("LED bulb 12W", "piece", 80, 140),
        ("Solar lamp", "piece", 700, 1400),
    ],
    "Home & Kitchen": [
        ("Steel pot set", "set", 1500, 3200),
        ("Tea glasses (6)", "box", 180, 350),
        ("Plastic chairs", "piece", 350, 600),
        ("Floor cushion (toshak)", "piece", 800, 1500),
        ("Thermos flask", "piece", 450, 900),
        ("Gas burner", "piece", 600, 1300),
    ],
    "Construction Supplies": [
        ("Cement bag 50kg", "bag", 550, 700),
        ("Steel rebar 12mm", "piece", 420, 600),
        ("Paint 4L", "can", 900, 1800),
        ("Bricks (per 100)", "lot", 700, 1000),
        ("PVC pipe 2in", "piece", 250, 450),
        ("Door lock", "piece", 200, 600),
    ],
    "Handicrafts & Carpets": [
        ("Hand-knotted rug 2x3m", "piece", 12000, 38000),
        ("Embroidered cushion cover", "piece", 350, 800),
        ("Lapis lazuli ring", "piece", 1500, 4500),
        ("Turkmen-style bag", "piece", 900, 2500),
        ("Wood-carved box", "piece", 600, 1800),
        ("Turquoise necklace", "piece", 1200, 3600),
    ],
}

SHOPS = [  # (business name, primary category)
    ("Noor Bakery", "Food & Bakery"),
    ("Shahr-e-Naw Fresh Market", "Fresh Produce"),
    ("Mandawi Dry Fruits", "Dry Fruits & Nuts"),
    ("Chicken Street Textiles", "Textiles & Clothing"),
    ("Kabul Phone Corner", "Electronics & Phones"),
    ("Khair Khana Home Goods", "Home & Kitchen"),
    ("Darulaman Building Supply", "Construction Supplies"),
    ("Turquoise Mountain Crafts", "Handicrafts & Carpets"),
    ("Wazir Akbar Khan Sweets", "Food & Bakery"),
    ("Qala-e-Fatullah Produce", "Fresh Produce"),
    ("Bagh-e-Bala Nuts", "Dry Fruits & Nuts"),
    ("Mirwais Maidan Fabrics", "Textiles & Clothing"),
    ("Hamid Electronics", "Electronics & Phones"),
    ("Karte Se Kitchenware", "Home & Kitchen"),
    ("Pul-e-Sukhta Hardware", "Construction Supplies"),
    ("Rabia Balkhi Carpets", "Handicrafts & Carpets"),
    ("Taimani Tandoor", "Food & Bakery"),
    ("Kart-e-Char Greengrocer", "Fresh Produce"),
    ("Pamir Raisin House", "Dry Fruits & Nuts"),
    ("Sadaf Tailoring", "Textiles & Clothing"),
    ("Afghan Mobile Hub", "Electronics & Phones"),
    ("Shirpur Household", "Home & Kitchen"),
    ("Jada-e-Maiwand Cement", "Construction Supplies"),
    ("Kuchi Craft Collective", "Handicrafts & Carpets"),
    ("Dasht-e-Barchi Bakery", "Food & Bakery"),
    ("Microrayan Market Garden", "Fresh Produce"),
    ("Paghman Orchard Direct", "Dry Fruits & Nuts"),
    ("Zarnegar Dress Shop", "Textiles & Clothing"),
    ("Solar Kabul", "Electronics & Phones"),
    ("Bibi Mahro Kitchen Store", "Home & Kitchen"),
    ("Qargha Paint & Tools", "Construction Supplies"),
    ("Lapis Lazuli Gallery", "Handicrafts & Carpets"),
    ("Sarai Shahzada Spices Bakery", "Food & Bakery"),
    ("Company Fresh Fruits", "Fresh Produce"),
    ("Nangarhar Nuts Depot", "Dry Fruits & Nuts"),
    ("Ansari Wool Traders", "Textiles & Clothing"),
    ("Chaman-e-Hozori Electronics", "Electronics & Phones"),
    ("Khushal Khan Homeware", "Home & Kitchen"),
    ("Shar-e-Naw Lumber", "Construction Supplies"),
    ("Herat Silk Road Crafts", "Handicrafts & Carpets"),
]

FIRST = [
    "Ahmad",
    "Mohammad",
    "Hamid",
    "Nasrin",
    "Zahra",
    "Farid",
    "Sohaila",
    "Jawid",
    "Mariam",
    "Bashir",
    "Laila",
    "Rahim",
    "Shabnam",
    "Qais",
    "Fatima",
    "Nazir",
    "Parwin",
    "Sayed",
    "Hila",
    "Omid",
]
LAST = [
    "Ahmadi",
    "Noori",
    "Rahimi",
    "Karimi",
    "Safi",
    "Sadat",
    "Popal",
    "Barakzai",
    "Wardak",
    "Amiri",
    "Yousufi",
    "Stanikzai",
    "Hashimi",
    "Faizi",
    "Azizi",
]
DISTRICT_WEIGHTS = {
    "PD1": 3,
    "PD2": 4,
    "PD3": 3,
    "PD4": 6,
    "PD5": 4,
    "PD6": 3,
    "PD7": 3,
    "PD8": 4,
    "PD10": 4,
    "PD11": 2,
    "PD12": 2,
    "PD13": 2,
    "PD15": 2,
    "PD16": 1,
    "PD17": 1,
    "PD22": 1,
}
BUSINESS_TYPES = ["Food", "Retail", "Tailoring", "Services", "Agriculture", "Crafts", "Electronics"]

# (code, construct, English, Dari, reverse-scored?)
QUESTIONS = [
    ("PU1", "PU", "Mobile money would make my business payments faster.", "پول موبایل پرداخت‌های کسب‌وکار من را سریع‌تر می‌کند.", False),
    ("PU2", "PU", "Mobile money would help me keep better records of sales.", "پول موبایل به من کمک می‌کند حساب فروش‌هایم را بهتر نگه دارم.", False),
    ("PU3", "PU", "Using mobile money would help me reach more customers.", "استفاده از پول موبایل به من کمک می‌کند به مشتریان بیشتری برسم.", False),
    ("PU4", "PU", "Mobile money would reduce the need to carry cash.", "پول موبایل نیاز به حمل پول نقد را کم می‌کند.", False),
    ("PEOU1", "PEOU", "Learning to use mobile money would be easy for me.", "یادگرفتن استفاده از پول موبایل برای من آسان است.", False),
    ("PEOU2", "PEOU", "I find mobile money apps or USSD menus clear and simple.", "منوهای پول موبایل برایم روشن و ساده است.", False),
    ("PEOU3", "PEOU", "I could use mobile money without help from others.", "می‌توانم بدون کمک دیگران از پول موبایل استفاده کنم.", False),
    ("PEOU4", "PEOU", "Mobile money is confusing to use.", "استفاده از پول موبایل گیج‌کننده است.", True),
    ("TR1", "TR", "I trust mobile money providers to keep my money safe.", "به شرکت‌های پول موبایل برای حفظ پولم اعتماد دارم.", False),
    ("TR2", "TR", "I believe transactions will be recorded correctly.", "باور دارم که معاملات درست ثبت می‌شوند.", False),
    ("TR3", "TR", "I am confident my personal information stays private.", "مطمئنم که اطلاعات شخصی من محفوظ می‌ماند.", False),
    ("TR4", "TR", "I worry about losing money through mobile money fraud.", "نگرانم که از طریق تقلب پول موبایل پولم را از دست بدهم.", True),
    ("CO1", "CO", "Mobile money transaction fees are affordable for my business.", "کارمزد معاملات پول موبایل برای کسب‌وکار من مناسب است.", False),
    ("CO2", "CO", "The cost of a phone and mobile data is manageable for me.", "هزینهٔ گوشی و انترنت موبایل برایم قابل تحمل است.", False),
    ("CO3", "CO", "Cash-out charges at agents are reasonable.", "کارمزد برداشت پول از نمایندگان معقول است.", False),
    ("CO4", "CO", "The fees make mobile money too expensive for small sales.", "کارمزدها پول موبایل را برای فروش‌های کوچک گران می‌کند.", True),
    ("AC1", "AC", "There are mobile money agents close to my shop or home.", "نمایندگان پول موبایل نزدیک دکان یا خانهٔ من هستند.", False),
    ("AC2", "AC", "Mobile network coverage where I work is reliable.", "پوشش شبکهٔ موبایل در محل کار من مطمئن است.", False),
    (
        "AC3",
        "AC",
        "Most of my customers and suppliers can also use mobile money.",
        "بیشتر مشتریان و تأمین‌کنندگان من هم می‌توانند از پول موبایل استفاده کنند.",
        False,
    ),
    (
        "WA1",
        "WA",
        "I intend to use mobile money for my business within the next 6 months.",
        "قصد دارم در شش ماه آینده از پول موبایل برای کسب‌وکارم استفاده کنم.",
        False,
    ),
    ("WA2", "WA", "I would accept mobile money payments from customers.", "پرداخت از طریق پول موبایل را از مشتریان می‌پذیرم.", False),
    (
        "WA3",
        "WA",
        "I would recommend mobile money to other small business owners.",
        "پول موبایل را به دیگر صاحبان کسب‌وکار کوچک پیشنهاد می‌کنم.",
        False,
    ),
]
